# Generated by Django 3.0.6 on 2020-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200519_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatatwo',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
