# Generated by Django 3.0.6 on 2020-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
